### PR TITLE
enable blackduck scan on app build

### PR DESCRIPTION
**Pull request by dasormeter**
Enable blackduck license and 3rd party lib security vulnerability scan for app build

### CODE REVIEW

**Comment by SamirTalwar** [comment]
Gonna let people who know what Black Duck is handle this one. 😉

**Comment by dasormeter** [comment]
@SamirTalwar blackduck scan successfully ran off this branch -- main thing to ensure is just that it is wired in CI, completes successfully, and is correctly identifying the calling project 
image
https://digitalasset.blackducksoftware.com/ui/versions/id:195e613d-b9c5-4a1f-b942-4337fc706264/view:bom?sortField=projectName&ascending=true&offset=0&inUseOnly=true

**Comment by SamirTalwar** [comment]
@dasormeter: Looks good from your screenshot, but I'm afraid I don't have access to that page.

**Comment by dasormeter** [comment]
> @dasormeter: Looks good from your screenshot, but I'm afraid I don't have access to that page.

hiya @SamirTalwar you should have access now

**Comment by SamirTalwar** [comment]
Looks good to me!

**Pull request merged**
